title: What did I get done this week
description: >- 
  Despite the fact that this website and the repo I'm building this site on is 
  public, this serves (for now) as a secret of the internet for me. I want to 
  hold myself accountable.
url: "https://mustafa-tariqk.github.io"
twitter_username: mustafa_tariqk
github_username:  mustafa-tariqk
linkedin_username: mustafa-tariqk

theme: minima
minima:
  skin: dark
plugins:
  - jekyll-feed

