title: Mustafa's Notes
description: What did you get done this week?
url: "https://mustafatariqk.com"
twitter_username: mustafa_tariqk
github_username: mustafa-tariqk

theme: minima
minima:
  skin: dark
plugins:
  - jekyll-feed
exclude:
  - templates