title: What did you get done this week
description: Reminders to myself.
url: "https://mustafa-tariqk.github.io"
twitter_username: mustafa_tariqk
github_username: mustafa-tariqk

theme: minima
minima:
  skin: dark
plugins:
  - jekyll-feed
