baseURL = 'https://mustafatariqk.com'
theme = ["github.com/janraasch/hugo-bearblog"]

title = "Mustafa's Notes"
author = "Mustafa Tariq"
languageCode = "en-US"

enableRobotsTXT = true

[params]
hideMadeWithLine = true
enablePostNavigator = true
