name: Append to README

on:
  push:
    branches:
      - main

jobs:
  append:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install -y curl sed

      - name: Download and append to file
        run: |
          curl https://raw.githubusercontent.com/mustafa-tariqk/mustafa-tariqk/main/README.md -o README.md
          sed -i '1s/^/---\nlayout: page\ntitle: README\npermalink: \/README\/\n---\n/' README.md

      - name: Commit and push if it changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git diff
          git diff --quiet || (git add -A && git commit -m "Appended content to README" && git push)